const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={messages:[],view:'all',updateReleaseUrl:'',updateAvailable:false,twitchSocket:null,twitchConnected:false,kickConnected:false,kickCanSend:false,kickEventSequence:0,kickPollTimer:null,kickOAuthTimer:null,kickRestoreTimer:null,twitchRoomId:'',kickChannelId:'',twitchBadges:{global:new Map(),channel:new Map(),roomId:''},kickBadges:{slug:'',loadingSlug:'',subscriber:[]},sevenTV:{global:new Map(),twitch:new Map(),kick:new Map(),globalLoaded:false},settings:{twitchChannel:'',mentionName:'',theme:'blue',fontSize:14,showBadges:true,badgeStyle:'color',showTime:true,highlightMentions:true,autoScroll:true,density:'comfortable'}};
const platformLogos={kick:'/assets/platform-kick.png',twitch:'/assets/platform-twitch.png'};
const viewInfo={
 all:{title:'All Chat',feed:'Unified feed',count:'countAll',icon:'all'},
 kick:{title:'Kick Chat',feed:'Kick feed',count:'countKick',icon:'kick'},
 twitch:{title:'Twitch Chat',feed:'Twitch feed',count:'countTwitch',icon:'twitch'},
 mentions:{title:'Mentions',feed:'Mention feed',count:'countMentions',icon:'mentions'}
};
function viewIconMarkup(view){if(view==='all')return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5.5 6.5h9a3 3 0 0 1 3 3v4.5a3 3 0 0 1-3 3H10l-3.2 2.4V17H5.5a3 3 0 0 1-3-3V9.5a3 3 0 0 1 3-3Z"/><path d="M9 3.5h9.5a3 3 0 0 1 3 3V11a3 3 0 0 1-2.2 2.9"/></svg>';if(view==='kick')return '';if(view==='twitch')return '';return '@'}
function updateViewTrigger(){const info=viewInfo[state.view]||viewInfo.all,icon=$('#viewTriggerIcon'),label=$('#viewTriggerLabel'),count=$('#viewTriggerCount'),srcCount=$('#'+info.count);if(icon){icon.className='viewIcon '+(info.icon==='kick'?'kickDotIcon':info.icon==='twitch'?'twitchDotIcon':info.icon==='mentions'?'mentionIcon':'all');icon.innerHTML=viewIconMarkup(state.view)}if(label)label.textContent=info.title;if(count)count.textContent=srcCount?.textContent||'0'}
function closeViewMenu(){const picker=$('#viewPicker'),trigger=$('#viewTrigger');if(picker)picker.classList.remove('open');if(trigger)trigger.setAttribute('aria-expanded','false')}

const themeLogos={blue:'/assets/theme-blue-raccoon.png',red:'/assets/theme-red-raccoon.png',purple:'/assets/theme-purple-raccoon.png',green:'/assets/theme-green-raccoon.png',pink:'/assets/theme-pink-raccoon.png'};
function setThemeLogo(){const img=$('#brandLogo');if(!img)return;const theme=state.settings.theme||'blue';img.src=themeLogos[theme]||themeLogos.blue;img.alt=`SleepyChat ${theme} theme logo`;img.dataset.theme=theme;}
const windowThemeColors={blue:'#06080d',red:'#0d0507',purple:'#0b0712',green:'#07100d',pink:'#180611'};
function applyWindowThemeColor(){const meta=$('#windowThemeColor');if(meta)meta.setAttribute('content',windowThemeColors[state.settings.theme]||windowThemeColors.blue)}
const sample=[
 {platform:'kick',user:'NeonWolf',text:'SleepyChat in the same window is actually clean 🔥',badges:[{type:'subscriber',text:'Subscriber',count:6},{type:'og',text:'OG'}],color:'#53fc18'},
 {platform:'twitch',user:'PixelPilot',text:'yo chat! multistream squad checking in Kappa',badges:[{set_id:'vip',id:'1'}],color:'#ff69b4',nativeEmotes:[{provider:'twitch',id:'25',name:'Kappa',image:'https://static-cdn.jtvnw.net/emoticons/v2/25/default/dark/2.0'}]},
 {platform:'kick',user:'ModMike',text:'Welcome everyone — keep it chill.',badges:[{type:'moderator',text:'Moderator'}],color:'#35c98f'},
 {platform:'twitch',user:'CoffeeRespawn',text:'@SleepyKev can you see both chats at once?',badges:[{set_id:'subscriber',id:'6'},{set_id:'founder',id:'0'}],color:'#d2691e'},
 {platform:'kick',user:'KickVIP',text:'VIP badge check from the Kick side.',badges:[{type:'vip',text:'VIP'}],color:'#c56bff'},
 {platform:'twitch',user:'PurplePanda',text:'Twitch side reporting in 👋',badges:[{set_id:'moderator',id:'1'}],color:'#8a2be2'},
 {platform:'kick',user:'SleepyKev',text:'Broadcaster badge is live too.',badges:[{type:'broadcaster',text:'Broadcaster'}],color:'#ff5d73'},
 {platform:'twitch',user:'FreshViewer',text:'regular viewer checking in',badges:[],color:'#1e90ff'}
];
function load(){seedTwitchBadgeFallbacks();try{Object.assign(state.settings,JSON.parse(localStorage.getItem('sleepychat-settings')||'{}'))}catch{};delete state.settings.kickRelay;if(!['blue','red','purple','green','pink'].includes(state.settings.theme))state.settings.theme='blue';if(!['color','mono'].includes(state.settings.badgeStyle))state.settings.badgeStyle='color';$('#twitchChannel').value=state.settings.twitchChannel||'';$('#mentionName').value=state.settings.mentionName||'';$('#themeSelect').value=state.settings.theme;$('#fontSize').value=state.settings.fontSize;$('#showBadges').checked=state.settings.showBadges!==false;$('#badgeStyle').value=state.settings.badgeStyle;$('#showTime').checked=state.settings.showTime;$('#highlightMentions').checked=state.settings.highlightMentions;$('#autoScroll').checked=state.settings.autoScroll;$('#density').value=state.settings.density||'comfortable';save();applyAppearance();render();loadTwitchBadges('')}
function save(){localStorage.setItem('sleepychat-settings',JSON.stringify(state.settings))}
const badgeMeta={broadcaster:{label:'HOST',icon:'◆',title:'Broadcaster'},mod:{label:'MOD',icon:'◆',title:'Moderator'},vip:{label:'VIP',icon:'♦',title:'VIP'},sub:{label:'SUB',icon:'★',title:'Subscriber'},og:{label:'OG',icon:'✦',title:'OG'},founder:{label:'FOUNDER',icon:'✦',title:'Founder'},verified:{label:'VERIFIED',icon:'✓',title:'Verified'},gifter:{label:'GIFTER',icon:'★',title:'Sub Gifter'},staff:{label:'STAFF',icon:'◆',title:'Staff'},partner:{label:'PARTNER',icon:'✓',title:'Partner'}};
function normalizeBadgeRole(value){const k=String(value||'').trim().toLowerCase().replace(/^badge[:_-]?/,'').split('/')[0].replace(/[\s-]+/g,'_');if(['broadcaster','owner','streamer','channel_owner'].includes(k))return'broadcaster';if(['moderator','mod'].includes(k))return'mod';if(['vip'].includes(k))return'vip';if(['subscriber','sub','subscription'].includes(k))return'sub';if(['og','original','original_gangster'].includes(k))return'og';if(['founder','founding_subscriber','founding_sub'].includes(k))return'founder';if(['verified','verification'].includes(k))return'verified';if(['sub_gifter','gifter','subgifter'].includes(k))return'gifter';if(['staff','admin','global_mod'].includes(k))return'staff';if(['partner','kpp'].includes(k))return'partner';return''}
function normalizeBadges(input,platform=''){const src=Array.isArray(input)?input:(typeof input==='string'?input.split(','):(input?[input]:[]));const out=[],seen=new Set();for(const item of src){let rawType='',setId='',id='',label='',image='',title='',count=0;if(typeof item==='string'){const bits=item.trim().split('/');rawType=bits[0]||'';setId=platform==='twitch'?rawType:'';id=platform==='twitch'?(bits[1]||'1'):''}else if(item&&typeof item==='object'){rawType=String(item.role??item.type??item.set_id??item.setId??item.name??item.badge??item.text??item.label??'').trim();setId=String(item.set_id??item.setId??(platform==='twitch'?rawType:'')).trim();id=String(item.id??item.version??item.badge_id??item.badgeId??'').trim();label=String(item.label??item.text??item.title??'').trim();title=String(item.title??item.description??label??'').trim();image=String(item.image_url_2x??item.image_url??item.imageUrl??item.url??item.image??item.badge_image?.src??'').trim();count=Number(item.count??item.months??item.info??0)||0}const role=normalizeBadgeRole(rawType||setId);if(!role&&!setId&&!image&&!label)continue;const key=[platform,setId||rawType,id,count,role,label].join('|');if(seen.has(key))continue;seen.add(key);const meta=badgeMeta[role];out.push({provider:platform,role,type:rawType,setId,id,count,label:label||(meta?.label||rawType||setId),title:title||(meta?.title||label||rawType||setId),image})}return out}
const twitchFallbackColors=['#1e90ff','#8a2be2','#5f9ea0','#d2691e','#ff7f50','#b22222','#daa520','#2e8b57','#ff69b4','#ff4500','#00bfff','#00c853','#9acd32','#c56bff'];
const kickFallbackColors=['#53fc18','#35c98f','#6ad5ff','#c56bff','#ff5d73','#ff9f43','#f5d76e','#7da6ff','#ff74c8','#3fe0c5','#b6ff63','#d695ff'];
function stableUserColor(platform,user){const palette=platform==='kick'?kickFallbackColors:twitchFallbackColors;let hash=2166136261;for(const ch of String(user||'')){hash^=ch.codePointAt(0);hash=Math.imul(hash,16777619)}return palette[(hash>>>0)%palette.length]}
function addMessage(m){const platform=(m.platform||'kick').toLowerCase(),user=String(m.user||m.username||m.sender||'Unknown'),actual=normalizeColor(m.color);m={id:crypto.randomUUID(),ts:Number(m.ts)||Date.now(),platform,user,text:String(m.text||m.message||m.content||''),badges:normalizeBadges(m.badges??m.badgeDetails??m.roles,platform),color:actual||stableUserColor(platform,user),colorSource:actual?'platform':'fallback',nativeEmotes:Array.isArray(m.nativeEmotes)?m.nativeEmotes:[]};state.messages.push(m);if(state.messages.length>1500)state.messages.splice(0,state.messages.length-1500);render();}
function hasBadge(m,role){const roles=(m.badges||[]).map(b=>typeof b==='string'?normalizeBadgeRole(b):b.role);if(role==='sub')return roles.includes('sub')||roles.includes('founder');if(role==='og')return roles.includes('og')||roles.includes('founder');return roles.includes(role)}
const twitchBuiltInBadges=new Map([
 ['broadcaster/1',{image:'https://static-cdn.jtvnw.net/badges/v1/5527c58c-fb7d-422d-b71b-f309dcb85cc1/2',title:'Broadcaster'}],
 ['moderator/1',{image:'https://static-cdn.jtvnw.net/badges/v1/3267646d-33f0-4b17-b3df-f923a41db1d0/2',title:'Moderator'}],
 ['vip/1',{image:'https://static-cdn.jtvnw.net/badges/v1/b817aba4-fad8-49e2-b88a-7cc744dfa6ec/2',title:'VIP'}],
 ['founder/0',{image:'https://static-cdn.jtvnw.net/badges/v1/511b78a9-ab37-472f-9569-457753bbe7d3/2',title:'Founder'}],
 ['founder/1',{image:'https://static-cdn.jtvnw.net/badges/v1/511b78a9-ab37-472f-9569-457753bbe7d3/2',title:'Founder'}],
 ['verified/1',{image:'https://static-cdn.jtvnw.net/badges/v1/d12a2e27-16f6-41d0-ab77-b780518f00a3/2',title:'Verified'}],
 ['subscriber/0',{image:'https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/2',title:'Subscriber'}],
 ['subscriber/1',{image:'https://static-cdn.jtvnw.net/badges/v1/5d9f2208-5dd8-11e7-8513-2ff4adfae661/2',title:'Subscriber'}]
]);
function seedTwitchBadgeFallbacks(){for(const [k,v] of twitchBuiltInBadges)if(!state.twitchBadges.global.has(k))state.twitchBadges.global.set(k,v)}
function collectTwitchBadgeCatalog(data){const map=new Map();let sets=[];if(Array.isArray(data))sets=data;else if(Array.isArray(data?.data))sets=data.data;else if(data?.badge_sets&&typeof data.badge_sets==='object')sets=Object.entries(data.badge_sets).map(([set_id,set])=>({set_id,versions:set?.versions||{}}));for(const set of sets){const setId=String(set?.set_id||set?.id||'');const versions=Array.isArray(set?.versions)?set.versions:Object.entries(set?.versions||{}).map(([id,v])=>({id,...v}));for(const v of versions){const id=String(v?.id??'1'),image=String(v?.image_url_2x||v?.image_url_1x||v?.image_url_4x||'');if(setId&&image)map.set(`${setId}/${id}`,{image,title:String(v?.title||v?.description||setId)})}}return map}
async function loadTwitchBadges(roomId=''){roomId=String(roomId||'').trim();seedTwitchBadgeFallbacks();try{const r=await fetch(`/api/twitch-badges${roomId?`?room_id=${encodeURIComponent(roomId)}`:''}`,{cache:'no-store'});if(!r.ok){render();return}const d=await r.json(),global=collectTwitchBadgeCatalog(d.global),channel=collectTwitchBadgeCatalog(d.channel);for(const [k,v] of global)state.twitchBadges.global.set(k,v);if(roomId){state.twitchBadges.roomId=roomId;state.twitchBadges.channel=channel}render()}catch{render()}}
function resolveTwitchBadge(b){const key=`${b.setId||b.type}/${b.id||'1'}`;let found=state.twitchBadges.channel.get(key)||state.twitchBadges.global.get(key);if(!found&&(b.role==='sub'||b.type==='subscriber'))found=state.twitchBadges.global.get('subscriber/1')||state.twitchBadges.global.get('subscriber/0');return found||null}
async function loadKickBadges(slug){slug=String(slug||'').trim().toLowerCase();if(!slug||slug===state.kickBadges.slug||slug===state.kickBadges.loadingSlug)return;state.kickBadges.loadingSlug=slug;try{const r=await fetch(`/api/kick-badges?slug=${encodeURIComponent(slug)}`,{cache:'no-store'});if(!r.ok)throw new Error('badge catalog');const d=await r.json(),list=(d.subscriber_badges||[]).map(x=>({months:Number(x.months)||0,image:String(x.badge_image?.src||'')})).filter(x=>x.image).sort((a,b)=>a.months-b.months);state.kickBadges.slug=slug;state.kickBadges.subscriber=list;render()}catch{}finally{if(state.kickBadges.loadingSlug===slug)state.kickBadges.loadingSlug=''}}
function resolveKickBadge(b){const role=b.role||normalizeBadgeRole(b.type||b.setId),count=Number(b.count)||0;if(b.image)return{image:`/api/kick-badge-image?url=${encodeURIComponent(b.image)}`,title:b.title};if(role==='sub'||b.type==='subscriber'){const list=state.kickBadges.subscriber;if(list.length){const months=count||1;let chosen=list[0];for(const x of list){if(x.months<=months)chosen=x;else break}return{image:`/api/kick-badge-image?url=${encodeURIComponent(chosen.image)}`,title:`Subscriber • ${months} month${months===1?'':'s'}`}}}if(role)return{image:`/api/kick-badge-image?role=${encodeURIComponent(role)}&count=${count}`,title:b.title||badgeMeta[role]?.title||b.label};return null}
function fallbackBadgeMarkup(role,meta,label,title){if(!role||!meta)return'';const visual=`<span class="badgeGlyph">${meta.icon}</span>`;return `<span class="badgeImageFallback badge role ${role} ${state.settings.badgeStyle==='mono'?'mono':''}" title="${esc(title||meta.title)}">${visual}<span>${esc(label||meta.label)}</span></span>`}
function renderRoleBadge(b,platform=''){if(state.settings.showBadges===false)return'';if(typeof b==='string')b=normalizeBadges([b],platform)[0]||{};const role=b.role||normalizeBadgeRole(b.type||b.setId),meta=badgeMeta[role],resolved=platform==='twitch'?(b.image?{image:b.image,title:b.title}:resolveTwitchBadge(b)):platform==='kick'?resolveKickBadge(b):(b.image?{image:b.image,title:b.title}:null);if(resolved?.image){const fallback=fallbackBadgeMarkup(role,meta,b.label,resolved.title||b.title);return `<span class="nativeBadge ${platform} role-${role||'unknown'}" title="${esc(resolved.title||b.title||meta?.title||b.label||'Badge')}"><img src="${esc(resolved.image)}" alt="${esc(b.label||meta?.title||'badge')}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.classList.add('badgeImageFailed')">${fallback}</span>`}if(!role||!meta)return'';const visual=`<span class="badgeGlyph">${meta.icon}</span>`,label=b.label||meta.label;return `<span class="badge role ${role} ${state.settings.badgeStyle==='mono'?'mono':''}" title="${esc(b.title||meta.title)}">${visual}<span>${esc(label)}</span></span>`}
function renderPlatformLogo(platform){platform=String(platform||'').toLowerCase();const src=platformLogos[platform];const alt=platform==='kick'?'Kick':platform==='twitch'?'Twitch':'Platform';return src?`<img class="platformLogo ${platform}" src="${esc(src)}" alt="${alt}" title="${alt}">`:`<span class="platformFallback">${esc(alt)}</span>`}
function messageGridStyle(){const compact=state.settings.density==='compact',cols=[];if(state.settings.showTime)cols.push(`calc(${compact?48:50}px * var(--chat-scale))`);cols.push('calc(16px * var(--chat-scale))');if(state.settings.showBadges)cols.push('max-content');cols.push('minmax(0,1fr)');return `grid-template-columns:${cols.join(' ')}`}
function normalizeColor(value){const c=String(value||'').trim();if(/^#[0-9a-f]{6}$/i.test(c)||/^#[0-9a-f]{3}$/i.test(c))return c;return''}
function parseIRCTags(raw){const tags={};if(!raw.startsWith('@'))return tags;const cut=raw.indexOf(' ');for(const p of raw.slice(1,cut).split(';')){const i=p.indexOf('=');const k=i<0?p:p.slice(0,i),v=i<0?'':p.slice(i+1);tags[k]=v.replace(/\\s/g,' ').replace(/\\:/g,';').replace(/\\\\/g,'\\').replace(/\\r/g,'\r').replace(/\\n/g,'\n')}return tags}
function twitchEmotesFromTag(tag,text){const out=[];for(const group of String(tag||'').split('/').filter(Boolean)){const split=group.indexOf(':');if(split<0)continue;const id=group.slice(0,split);for(const range of group.slice(split+1).split(',')){const [a,b]=range.split('-').map(Number);if(!Number.isInteger(a)||!Number.isInteger(b)||b<a)continue;out.push({provider:'twitch',id,start:a,end:b,name:text.slice(a,b+1),image:`https://static-cdn.jtvnw.net/emoticons/v2/${encodeURIComponent(id)}/default/dark/2.0`})}}return out.sort((a,b)=>a.start-b.start)}
function normalizeNativeEmotes(input){const src=Array.isArray(input)?input:(input?[input]:[]),out=[];for(const e of src){if(!e)continue;if(typeof e==='string')continue;const id=String(e.id??e.emote_id??e.emoteId??'').trim(),name=String(e.name??e.code??e.text??e.alias??'').trim();let image=String(e.image_url??e.imageUrl??e.url??e.image??e.images?.url_2x??e.images?.url_1x??e.host?.url??'').trim();if(image.startsWith('//'))image='https:'+image;if(image&&e.host?.files&&Array.isArray(e.host.files)&&!/[.](?:png|webp|gif|avif)(?:\?|$)/i.test(image)){const file=e.host.files.find(f=>/2x\.(?:webp|avif|png|gif)$/i.test(f.name||''))||e.host.files.find(f=>/1x\./i.test(f.name||''))||e.host.files[0];if(file?.name)image=image.replace(/\/$/,'')+'/'+file.name}if(id||name||image)out.push({provider:e.provider||'kick',id,name,image,start:Number.isInteger(e.start)?e.start:undefined,end:Number.isInteger(e.end)?e.end:undefined})}return out}
function kickMarkup(text){const emotes=[];let plain='',last=0;const re=/\[emote:(\d+):([^\]]+)\]/g;let m;while((m=re.exec(text))){plain+=text.slice(last,m.index);const start=plain.length;plain+=m[2];emotes.push({provider:'kick',id:m[1],name:m[2],start,end:start+m[2].length-1,image:`https://files.kick.com/emotes/${encodeURIComponent(m[1])}/fullsize`});last=m.index+m[0].length}plain+=text.slice(last);return{text:plain,emotes}}
function sevenTVImage(e){const d=e?.data||e||{},host=d.host||e?.host||{},base=String(host.url||d.host_url||e?.host_url||'');const files=host.files||d.files||e?.files||[];if(!base)return String(e?.image_url||e?.url||'');let u=base.startsWith('//')?'https:'+base:base;const file=files.find(f=>/2x\.(?:webp|avif|png|gif)$/i.test(f.name||''))||files.find(f=>/1x\.(?:webp|avif|png|gif)$/i.test(f.name||''))||files[0];return file?.name?u.replace(/\/$/,'')+'/'+file.name:u}
function collect7TV(data){const sets=[];if(data?.emote_set)sets.push(data.emote_set);if(data?.emoteSet)sets.push(data.emoteSet);if(Array.isArray(data?.emote_sets))sets.push(...data.emote_sets);if(Array.isArray(data?.emotes))sets.push(data);const map=new Map();for(const set of sets){for(const e of set?.emotes||[]){const name=String(e?.name||e?.data?.name||'').trim(),image=sevenTVImage(e);if(name&&image)map.set(name,{name,image,provider:'7tv',flags:Number(e?.flags||e?.data?.flags||0)})}}return map}
async function load7TVGlobal(){if(state.sevenTV.globalLoaded)return;state.sevenTV.globalLoaded=true;try{const r=await fetch('/api/7tv?global=1');if(r.ok){state.sevenTV.global=collect7TV(await r.json());render()}else state.sevenTV.globalLoaded=false}catch{state.sevenTV.globalLoaded=false}}
async function load7TV(platform,id){platform=String(platform||'').toLowerCase();id=String(id||'').trim();if(!['twitch','kick'].includes(platform)||!/^\d+$/.test(id))return;load7TVGlobal();try{const r=await fetch(`/api/7tv?platform=${encodeURIComponent(platform)}&id=${encodeURIComponent(id)}`);if(r.ok){state.sevenTV[platform]=collect7TV(await r.json());render()}}catch{}}
function sevenTVFor(platform){return new Map([...state.sevenTV.global,...(state.sevenTV[platform]||new Map())])}
function renderMentionPlain(text){text=String(text||'');const re=mentionRegex(true);if(!re)return esc(text);let out='',last=0;text.replace(re,(match,prefix,name,offset)=>{out+=esc(text.slice(last,offset));out+=esc(prefix)+`<mark class="mentionToken">${esc(name)}</mark>`;last=offset+match.length;return match});return out+esc(text.slice(last))}
function renderTokenizedPlain(text,platform,nativeNames){const seven=sevenTVFor(platform);return String(text||'').split(/(\s+)/).map(token=>{if(/^\s+$/.test(token))return token;const native=nativeNames.get(token);if(native?.image)return `<img class="chatEmote native ${platform}" src="${esc(native.image)}" alt="${esc(token)}" title="${esc(token)}">`;const e=seven.get(token);if(e?.image)return `<img class="chatEmote sevenTV" src="${esc(e.image)}" alt="${esc(token)}" title="7TV • ${esc(token)}">`;return renderMentionPlain(token)}).join('')}
function renderRichMessage(m){const text=String(m.text||''),native=Array.isArray(m.nativeEmotes)?m.nativeEmotes:[],pos=native.filter(e=>Number.isInteger(e.start)&&Number.isInteger(e.end)).sort((a,b)=>a.start-b.start),names=new Map(native.filter(e=>e.name&&e.image).map(e=>[e.name,e]));if(!pos.length)return renderTokenizedPlain(text,m.platform,names);let out='',cursor=0;for(const e of pos){if(e.start<cursor||e.start>=text.length)continue;out+=renderTokenizedPlain(text.slice(cursor,e.start),m.platform,names);const label=text.slice(e.start,Math.min(text.length,e.end+1));out+=e.image?`<img class="chatEmote native ${m.platform}" src="${esc(e.image)}" alt="${esc(label)}" title="${esc(e.name||label)}">`:renderMentionPlain(label);cursor=Math.min(text.length,e.end+1)}out+=renderTokenizedPlain(text.slice(cursor),m.platform,names);return out}
function broadcasterName(){return (state.settings.mentionName||state.settings.twitchChannel||'').trim().replace(/^@+/,'')}
function mentionRegex(global=false){const key=broadcasterName();if(!key)return null;const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|[^A-Za-z0-9_])(@?${escaped})(?=$|[^A-Za-z0-9_])`,global?'gi':'i')}
function isMention(m){const re=mentionRegex(false);return !!re&&re.test(String(m.text||''))}
function renderMessageText(text){return renderMentionPlain(text)}
function visible(m){if(state.view==='kick'&&m.platform!=='kick')return false;if(state.view==='twitch'&&m.platform!=='twitch')return false;if(state.view==='mentions'&&!isMention(m))return false;const q=$('#search').value.trim().toLowerCase();if(q&&!(`${m.user} ${m.text}`.toLowerCase().includes(q)))return false;const r=$('#roleFilter').value;if(r==='mods'&&!hasBadge(m,'mod'))return false;if(r==='subs'&&!hasBadge(m,'sub'))return false;if(r==='vips'&&!hasBadge(m,'vip'))return false;if(r==='ogs'&&!hasBadge(m,'og'))return false;if(r==='broadcasters'&&!hasBadge(m,'broadcaster'))return false;return true}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const feed=$('#feed'),items=state.messages.filter(visible);$('#countAll').textContent=state.messages.length;$('#countKick').textContent=state.messages.filter(x=>x.platform==='kick').length;$('#countTwitch').textContent=state.messages.filter(x=>x.platform==='twitch').length;$('#countMentions').textContent=state.messages.filter(isMention).length;updateViewTrigger();$('#chatMeta').textContent=items.length?`${items.length} visible • ${state.messages.length} total`:'Waiting for chat…';if(!items.length){feed.innerHTML='<div class="empty"><div><strong>No messages yet</strong>Connect a platform or run Demo Mode to preview the unified feed.</div></div>';return}const gridStyle=messageGridStyle();feed.innerHTML=items.map(m=>{const time=new Date(m.ts).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});const mention=isMention(m)&&state.settings.highlightMentions;const roleBadges=state.settings.showBadges?(m.badges||[]).map(b=>renderRoleBadge(b,m.platform)).join(''):'';const timeCell=state.settings.showTime?`<div class="stamp">${time}</div>`:'';const badgeCell=state.settings.showBadges?`<div class="badgeSlot">${roleBadges}</div>`:'';return `<div class="message ${mention?'mention':''} ${state.settings.density==='compact'?'compact':''}" style="${gridStyle}">${timeCell}<div class="platformSlot">${renderPlatformLogo(m.platform)}</div>${badgeCell}<div class="msgBody"><span class="user" style="${m.color?`color:${esc(m.color)}`:''}">${esc(m.user)}</span><span class="text">${renderRichMessage(m)}</span></div></div>`}).join('');if(state.settings.autoScroll)feed.scrollTop=feed.scrollHeight}
function setView(v){if(!viewInfo[v])v='all';state.view=v;$$('.viewOption').forEach(b=>b.classList.toggle('active',b.dataset.view===v));const info=viewInfo[v];$('#viewTitle').textContent=info.title;$('#feedLabel').textContent=info.feed;closeViewMenu();render();updateViewTrigger()}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function demo(){sample.forEach((m,i)=>setTimeout(()=>addMessage(m),i*280));toast('Demo chat started')}
function connectTwitch(){disconnectTwitch();const channel=(state.settings.twitchChannel||'').trim().toLowerCase().replace(/^#/,'');if(!channel){openModal('connections');toast('Enter a Twitch channel first');return}const nick='justinfan'+Math.floor(10000+Math.random()*80000);const ws=new WebSocket('wss://irc-ws.chat.twitch.tv:443');state.twitchSocket=ws;$('#twitchStatus').textContent='Connecting…';ws.onopen=()=>{ws.send('CAP REQ :twitch.tv/tags twitch.tv/commands');ws.send('PASS SCHMOOPIIE');ws.send('NICK '+nick);ws.send('JOIN #'+channel)};ws.onmessage=e=>{for(const line of String(e.data).split('\r\n')){if(line.startsWith('PING')){ws.send('PONG :tmi.twitch.tv');continue}if(line.includes(' ROOMSTATE #')){const tags=parseIRCTags(line),room=tags['room-id'];if(room&&room!==state.twitchRoomId){state.twitchRoomId=room;load7TV('twitch',room);loadTwitchBadges(room)}continue}if(!line.includes(' PRIVMSG #'))continue;const parsed=parseIRC(line);if(parsed)addMessage(parsed)}};ws.onerror=()=>{$('#twitchStatus').textContent='Connection error';$('#twitchStatus').classList.remove('live')};ws.onclose=()=>{state.twitchConnected=false;$('#twitchStatus').textContent='Not connected';$('#twitchStatus').classList.remove('live');$('#twitchConnectBtn').textContent='Connect'};setTimeout(()=>{if(ws.readyState===WebSocket.OPEN){state.twitchConnected=true;$('#twitchStatus').textContent='Live • #'+channel;$('#twitchStatus').classList.add('live');$('#twitchConnectBtn').textContent='Disconnect';toast('Twitch chat connected')}},900)}
function disconnectTwitch(){if(state.twitchSocket){try{state.twitchSocket.close()}catch{}state.twitchSocket=null}state.twitchConnected=false}
function parseIRC(line){const tags=parseIRCTags(line);if(line.startsWith('@'))line=line.slice(line.indexOf(' ')+1);const m=line.match(/^:([^!]+)![^ ]+ PRIVMSG #[^ ]+ :(.*)$/);if(!m)return null;let text=m[2];if(text.startsWith('\u0001ACTION ')&&text.endsWith('\u0001'))text=text.slice(8,-1);const raw=(tags.badges||'').split(',').filter(Boolean).map(token=>{const [set_id,id='1']=token.split('/');return{set_id,id}}),roles=raw.map(x=>normalizeBadgeRole(x.set_id));if(tags.mod==='1'&&!roles.includes('mod')&&!roles.includes('broadcaster'))raw.push({set_id:'moderator',id:'1'});if(tags.subscriber==='1'&&!roles.includes('sub')&&!roles.includes('founder'))raw.push({set_id:'subscriber',id:'1'});return{platform:'twitch',user:tags['display-name']||m[1],userId:tags['user-id']||'',text,badges:raw,color:tags.color||'',nativeEmotes:twitchEmotesFromTag(tags.emotes,text)}}
function adaptKickMessage(m){m=m||{};const sender=m.sender||m.user_data||m.chatter||{},identity=sender.identity||m.identity||{},broadcaster=m.broadcaster||m.channel||{};let text=String(m.text??m.message??m.content??m.body??'');const markup=kickMarkup(text);text=markup.text;const native=normalizeNativeEmotes(m.emotes??m.message_emotes??m.emote_data??m.metadata?.emotes??sender.emotes??identity.emotes??[]);native.push(...markup.emotes);const channelId=String(m.broadcaster_user_id??m.channel_id??broadcaster.user_id??broadcaster.id??''),channelSlug=String(m.broadcaster_slug??m.channel_slug??broadcaster.channel_slug??broadcaster.slug??'').trim();if(/^\d+$/.test(channelId)&&channelId!==state.kickChannelId){state.kickChannelId=channelId;load7TV('kick',channelId)}if(channelSlug)loadKickBadges(channelSlug);const badges=[...(Array.isArray(identity.badges)?identity.badges:(m.badges??m.roles??sender.badges??[]))];if(sender.is_verified&&!badges.some(b=>normalizeBadgeRole(b?.type??b)==='verified'))badges.push({type:'verified',text:'Verified'});return{platform:'kick',user:m.user||m.username||sender.username||sender.name||sender.display_name||'Unknown',userId:String(sender.user_id??sender.id??''),text,badges,color:identity.username_color||m.username_color||m.color||sender.username_color||sender.color||'',nativeEmotes:native,ts:m.ts||m.timestamp||m.created_at||Date.now()}}
function stopKickOAuthPolling(){if(state.kickOAuthTimer){clearTimeout(state.kickOAuthTimer);state.kickOAuthTimer=null}}
function stopKickEventPolling(){if(state.kickPollTimer){clearTimeout(state.kickPollTimer);state.kickPollTimer=null}}
function stopKickRestorePolling(){if(state.kickRestoreTimer){clearTimeout(state.kickRestoreTimer);state.kickRestoreTimer=null}}
function updateComposer(){const input=$('#composer'),btn=$('#sendBtn'),notice=$('#integrationNotice');if(!input||!btn)return;const connected=state.kickConnected;input.disabled=!connected;btn.disabled=!connected;input.placeholder=connected?'Message Kick chat…':'Connect Kick to send messages…';if(notice)notice.innerHTML=connected?(state.kickCanSend?'<strong>Kick sending enabled</strong> • Messages are sent as your connected Kick account. Press Enter or choose Send.':'<strong>Kick connected</strong> • Type a message and press Send. If Kick needs chat permission, SleepyChat will open authorization automatically.'):'<strong>Kick sending</strong> • Connect Kick to send messages. Twitch is still read-only until Twitch OAuth sending is added.'}
function applyKickState(s,quiet=false){s=s||{};const status=$('#kickStatus'),btn=$('#kickConnectBtn'),connected=!!s.connected,pending=!!s.oauth_pending||s.status==='authorizing'||s.status==='finishing';state.kickConnected=connected;state.kickCanSend=connected&&!!s.can_send_chat;updateComposer();status.classList.toggle('live',connected&&!pending);if(pending){status.textContent=s.status==='finishing'?'Finishing authorization…':'Authorize in browser…';btn.textContent='Waiting for Kick…';btn.disabled=true;return}if(connected){const user=String(s.kick_username||'').trim();status.textContent=user?'Live • @'+user:'Connected';btn.textContent=state.kickCanSend?'Disconnect':'Enable Sending';btn.disabled=false;if(!quiet)toast(user?'Kick connected as @'+user:'Kick chat connected');startKickEventPolling();return}stopKickEventPolling();btn.disabled=false;btn.textContent='Connect with Kick';if(s.status==='checking'||s.status==='refreshing'){status.textContent='Checking saved login…';return}if(s.status==='reconnect_required'){status.textContent='Reconnect required';return}if(s.status==='degraded'){status.textContent='Service unavailable';return}status.textContent='Not connected'}
async function readKickResponse(res){let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error(body.error||'Kick service request failed');return body}
async function connectKick(){stopKickOAuthPolling();stopKickRestorePolling();$('#kickStatus').textContent='Starting authorization…';$('#kickStatus').classList.remove('live');$('#kickConnectBtn').textContent='Opening Kick…';$('#kickConnectBtn').disabled=true;try{const res=await fetch('/api/kick/oauth/start',{method:'POST',cache:'no-store'});const s=await readKickResponse(res);applyKickState(s,true);pollKickOAuth()}catch(e){applyKickState({status:'degraded'},true);toast(e?.message||'Could not start Kick authorization')}}
async function pollKickOAuth(){stopKickOAuthPolling();try{const res=await fetch('/api/kick/oauth/status',{method:'POST',cache:'no-store'});const s=await readKickResponse(res);applyKickState(s,true);if(s.oauth_pending||s.status==='authorizing'||s.status==='finishing'){state.kickOAuthTimer=setTimeout(pollKickOAuth,1000);return}if(s.connected){stopKickOAuthPolling();toast(s.kick_username?'Kick connected as @'+s.kick_username:'Kick chat connected');return}if(s.last_error)toast(s.last_error)}catch(e){applyKickState({status:'degraded'},true);toast(e?.message||'Could not finish Kick authorization')}}
async function pollKickEvents(){state.kickPollTimer=null;if(!state.kickConnected)return;try{const res=await fetch('/api/kick/events/poll?after='+encodeURIComponent(state.kickEventSequence),{cache:'no-store'});if(res.ok){const d=await res.json();const events=Array.isArray(d.events)?d.events:[];for(const ev of events){const seq=Number(ev.sequence)||0;if(seq>state.kickEventSequence)state.kickEventSequence=seq;if(ev.event_type==='chat.message.sent'&&ev.payload)addMessage(adaptKickMessage(ev.payload))}const latest=Number(d.latest_sequence)||0;if(latest>state.kickEventSequence)state.kickEventSequence=latest}}catch{}if(state.kickConnected)state.kickPollTimer=setTimeout(pollKickEvents,650)}
function startKickEventPolling(){if(state.kickPollTimer||!state.kickConnected)return;state.kickPollTimer=setTimeout(pollKickEvents,50)}
async function restoreKickConnection(attempt=0){stopKickRestorePolling();try{const res=await fetch('/api/kick/status',{cache:'no-store'});const s=await readKickResponse(res);applyKickState(s,true);if(s.connected)return;if(s.oauth_pending||s.status==='authorizing'||s.status==='finishing'){pollKickOAuth();return}if((s.status==='checking'||s.status==='refreshing')&&attempt<20){state.kickRestoreTimer=setTimeout(()=>restoreKickConnection(attempt+1),1000)}}catch{applyKickState({status:'degraded'},true)}}
async function disconnectKick(){stopKickOAuthPolling();stopKickRestorePolling();stopKickEventPolling();const btn=$('#kickConnectBtn');btn.disabled=true;btn.textContent='Disconnecting…';try{const res=await fetch('/api/kick/disconnect',{method:'POST',cache:'no-store'});const s=await readKickResponse(res);state.kickEventSequence=0;applyKickState(s,true);toast('Kick disconnected')}catch(e){btn.disabled=false;toast(e?.message||'Could not disconnect Kick');restoreKickConnection()}}
async function upgradeKickSending(){stopKickOAuthPolling();toast('Refreshing Kick permissions…');try{await fetch('/api/kick/disconnect',{method:'POST'}).catch(()=>{});state.kickConnected=false;state.kickCanSend=false;updateComposer();await connectKick()}catch(e){toast(e?.message||'Could not refresh Kick permissions')}}
async function sendKickMessage(){const input=$('#composer'),btn=$('#sendBtn');const content=String(input?.value||'').trim();if(!content)return;if(!state.kickConnected){toast('Connect Kick first');return}btn.disabled=true;input.disabled=true;try{const res=await fetch('/api/kick/chat/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});let body={};try{body=await res.json()}catch{}if(!res.ok){const msg=String(body.error||'Could not send Kick message');const low=msg.toLowerCase();if(low.includes('chat write')||low.includes('chat_write')){state.kickCanSend=false;toast('Kick needs Send chat messages permission. Opening a fresh authorization…');await upgradeKickSending();return}if(low.includes('reconnect')||low.includes('unauthorized')){toast('Kick authorization expired. Reconnecting…');await upgradeKickSending();return}throw new Error(msg)}state.kickCanSend=true;input.value='';toast('Sent to Kick')}catch(e){toast(e?.message||'Could not send Kick message')}finally{updateComposer();input?.focus()}}
function setUpdateCard(kind,status,message){const dot=$('#updateDot'),label=$('#updateStatus'),msg=$('#updateMessage');if(dot)dot.className='platformDot updateDot '+kind;if(label){label.className='status updateStatus '+kind;label.textContent=status}if(msg)msg.textContent=message||''}
async function checkForUpdates(quiet=false){const btn=$('#updateBtn');if(!btn)return;btn.disabled=true;btn.textContent='Checking…';setUpdateCard('checking','Checking…','Checking GitHub Releases for the latest SleepyChat version.');try{const res=await fetch('/api/update/check',{cache:'no-store'});const info=await res.json();if(!res.ok)throw new Error(info?.message||'Unable to check for updates');state.updateAvailable=!!info.update_available;state.updateReleaseUrl=String(info.release_url||'');if(state.updateAvailable){const version=String(info.latest_version||'').trim();btn.textContent='View Update';btn.title='Open the latest SleepyChat release on GitHub';setUpdateCard('warn','Update available',info.message||(version?`SleepyChat ${version} is available.`:'A newer SleepyChat release is available.'));if(!quiet)toast(info.message||'A SleepyChat update is available');return}if(info.status==='up_to_date'||info.status==='ahead'){btn.textContent='Check Now';btn.title='Check GitHub Releases again';setUpdateCard('good',info.status==='ahead'?'Ahead of release':'Up to date',info.message||`SleepyChat ${String(info.current_version||'1.0.0')} is up to date.`);if(!quiet)toast(info.message||'SleepyChat is up to date');return}state.updateAvailable=false;btn.textContent='Check Now';btn.title='Check GitHub Releases again';setUpdateCard('checking','Ready',info.message||'Ready to check GitHub Releases.');if(!quiet&&info.message)toast(info.message)}catch(e){state.updateAvailable=false;state.updateReleaseUrl='';btn.textContent='Retry';btn.title='Try the update check again';const message=e?.message||'Unable to check for updates';setUpdateCard('bad','Check failed',message);if(!quiet)toast(message)}finally{btn.disabled=false}}
function handleUpdateButton(){if(state.updateAvailable&&state.updateReleaseUrl){window.open(state.updateReleaseUrl,'_blank','noopener');return}checkForUpdates(false)}
async function openSleepyChatGitHub(){try{await fetch('/api/update/open-repository',{method:'POST'})}catch{window.open('https://github.com/SleepyKevy/SleepyChat','_blank','noopener')}}
function openModal(name){$('#'+name+'Modal').classList.add('open')}
function closeModals(){$$('.modalWrap').forEach(x=>x.classList.remove('open'))}
function applyAppearance(){document.body.dataset.theme=state.settings.theme||'blue';setThemeLogo();applyWindowThemeColor();const chatSize=Number(state.settings.fontSize)||14;document.documentElement.style.setProperty('--chat-font-size',chatSize+'px');document.documentElement.style.setProperty('--chat-scale',String(chatSize/14));$('#feed').style.fontSize=chatSize+'px';render()}
$$('.viewOption').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#viewTrigger').onclick=e=>{e.stopPropagation();const picker=$('#viewPicker'),open=!picker.classList.contains('open');picker.classList.toggle('open',open);$('#viewTrigger').setAttribute('aria-expanded',open?'true':'false')};document.addEventListener('click',e=>{if(!e.target.closest('#viewPicker'))closeViewMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeViewMenu()});$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modalWrap').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});
$('#demoBtn').onclick=demo;$('#kickConnectBtn').onclick=()=>state.kickConnected?(state.kickCanSend?disconnectKick():upgradeKickSending()):connectKick();$('#kickDemoBtn').onclick=()=>{sample.filter(x=>x.platform==='kick').forEach((m,i)=>setTimeout(()=>addMessage(m),i*250));toast('Kick demo messages added')};$('#twitchConnectBtn').onclick=()=>state.twitchConnected?disconnectTwitch():connectTwitch();$('#sendBtn').onclick=sendKickMessage;$('#composer').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendKickMessage()}});
$('#saveConnections').onclick=()=>{state.settings.twitchChannel=$('#twitchChannel').value.trim();state.settings.mentionName=$('#mentionName').value.trim()||state.settings.twitchChannel;$('#mentionName').value=state.settings.mentionName;save();closeModals();render();toast('Connections saved')};
$('#search').oninput=render;$('#roleFilter').onchange=render;$('#density').onchange=e=>{state.settings.density=e.target.value;save();render()};
$('#themeSelect').onchange=e=>{state.settings.theme=e.target.value;save();applyAppearance();toast('Theme changed to '+e.target.options[e.target.selectedIndex].text)};$('#fontSize').oninput=e=>{state.settings.fontSize=Number(e.target.value);save();applyAppearance()};$('#showBadges').onchange=e=>{state.settings.showBadges=e.target.checked;save();render()};$('#badgeStyle').onchange=e=>{state.settings.badgeStyle=e.target.value;save();render()};$('#showTime').onchange=e=>{state.settings.showTime=e.target.checked;save();render()};$('#highlightMentions').onchange=e=>{state.settings.highlightMentions=e.target.checked;save();render()};$('#autoScroll').onchange=e=>{state.settings.autoScroll=e.target.checked;save()};
$('#updateBtn').onclick=handleUpdateButton;$('#githubBtn').onclick=openSleepyChatGitHub;$('#clearBtn').onclick=()=>{state.messages=[];render();toast('Chat cleared')};$('#dataBtn').onclick=()=>fetch('/api/open-data',{method:'POST'});
$('#exportBtn').onclick=()=>{if(!state.messages.length){toast('No chat to export');return}const rows=state.messages.map(m=>`${new Date(m.ts).toISOString()}\t${m.platform}\t${m.user}\t${m.text.replace(/\r?\n/g,' ')}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:'text/plain'}));a.download=`SleepyChat-${new Date().toISOString().replace(/[:.]/g,'-')}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
setInterval(()=>fetch('/api/ping',{method:'POST'}).catch(()=>{}),4000);let closingSent=false;const notifyClosing=()=>{if(closingSent)return;closingSent=true;try{navigator.sendBeacon('/api/window-closing',new Blob([], {type:'application/octet-stream'}))}catch{fetch('/api/window-closing',{method:'POST',keepalive:true}).catch(()=>{})}};window.addEventListener('pagehide',notifyClosing,{once:true});fetch('/api/status').then(r=>r.json()).then(s=>{$('#runtimePill').innerHTML=`<span class="statusLight" aria-hidden="true"></span><span class="runtimeText">${esc(s.name)} ${esc(s.version)} ready</span>`}).catch(()=>{});load();restoreKickConnection();setTimeout(()=>checkForUpdates(true),1200);
